// Precomputed hue-rotation keyframes for the login orb (README: "full hue-rotate cycle
// 0deg -> 360deg, 10s linear loop"). Generated by rotating the H channel of the login
// orb's OKLCH tokens in 30deg steps and converting each to sRGB — see the tokens.ts
// header for the conversion method. 13 stops (12 steps + wrap-back to stop 0), crossfaded
// between adjacent stops at runtime — coarser than a true continuous hue-rotate, but
// imperceptible at a 10s cycle and far cheaper than animating gradient stop colors
// directly (react-native-svg's <Stop> has no native host instance to animate on-device).

export const midHueStops = [
  'rgba(189, 211, 242, 1)', 'rgba(207, 204, 241, 1)', 'rgba(223, 199, 231, 1)', 'rgba(235, 196, 215, 1)',
  'rgba(240, 197, 197, 1)', 'rgba(238, 200, 181, 1)', 'rgba(227, 206, 173, 1)', 'rgba(212, 212, 175, 1)',
  'rgba(193, 217, 186, 1)', 'rgba(178, 220, 203, 1)', 'rgba(171, 220, 221, 1)', 'rgba(176, 216, 235, 1)',
  'rgba(189, 211, 242, 1)',
];

export const loHueStops = [
  'rgba(163, 182, 209, 1)', 'rgba(178, 176, 208, 1)', 'rgba(193, 172, 199, 1)', 'rgba(203, 169, 185, 1)',
  'rgba(208, 169, 169, 1)', 'rgba(205, 172, 156, 1)', 'rgba(196, 177, 149, 1)', 'rgba(182, 183, 150, 1)',
  'rgba(167, 188, 160, 1)', 'rgba(153, 190, 175, 1)', 'rgba(147, 190, 190, 1)', 'rgba(151, 186, 203, 1)',
  'rgba(163, 182, 209, 1)',
];

export const glowHueStops = [
  'rgba(185, 211, 249, 0.28)', 'rgba(206, 203, 247, 0.28)', 'rgba(226, 197, 235, 0.28)', 'rgba(240, 194, 216, 0.28)',
  'rgba(246, 194, 194, 0.28)', 'rgba(243, 198, 175, 0.28)', 'rgba(231, 205, 165, 0.28)', 'rgba(212, 213, 167, 0.28)',
  'rgba(190, 219, 181, 0.28)', 'rgba(171, 222, 201, 0.28)', 'rgba(163, 222, 223, 0.28)', 'rgba(168, 217, 240, 0.28)',
  'rgba(185, 211, 249, 0.28)',
];

export const coreHueStops = [
  'rgba(230, 243, 255, 0.45)', 'rgba(240, 239, 255, 0.45)', 'rgba(251, 236, 255, 0.45)', 'rgba(255, 234, 245, 0.45)',
  'rgba(255, 234, 234, 0.45)', 'rgba(255, 236, 225, 0.45)', 'rgba(253, 240, 220, 0.45)', 'rgba(243, 244, 221, 0.45)',
  'rgba(232, 247, 228, 0.45)', 'rgba(224, 249, 238, 0.45)', 'rgba(220, 248, 249, 0.45)', 'rgba(222, 246, 255, 0.45)',
  'rgba(230, 243, 255, 0.45)',
];
